export default {
  login: 'Amir-ali-basic',
  id: 63121897,
  node_id: 'MDQ6VXNlcjYzMTIxODk3',
  avatar_url: 'https://avatars.githubusercontent.com/u/63121897?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Amir-ali-basic',
  html_url: 'https://github.com/Amir-ali-basic',
  followers_url: 'https://api.github.com/users/Amir-ali-basic/followers',
  following_url:
    'https://api.github.com/users/Amir-ali-basic/following{/other_user}',
  gists_url: 'https://api.github.com/users/Amir-ali-basic/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Amir-ali-basic/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/Amir-ali-basic/subscriptions',
  organizations_url: 'https://api.github.com/users/Amir-ali-basic/orgs',
  repos_url: 'https://api.github.com/users/Amir-ali-basic/repos',
  events_url: 'https://api.github.com/users/Amir-ali-basic/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Amir-ali-basic/received_events',
  type: 'User',
  site_admin: false,
  name: 'Amir Alibasic',
  company: 'QQRIQ',
  blog: 'https://linktr.ee/AlibAmir',
  location: 'Podgorica , Montenegro',
  email: null,
  hireable: null,
  bio: 'I can write Hello World! in any programming language.',
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 4,
  following: 4,
  created_at: '2020-04-03T18:34:22Z',
  updated_at: '2021-06-06T20:29:01Z',
};
