export default [
  {
    login: 'PeacefulNoob',
    id: 59912238,
    node_id: 'MDQ6VXNlcjU5OTEyMjM4',
    avatar_url: 'https://avatars.githubusercontent.com/u/59912238?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/PeacefulNoob',
    html_url: 'https://github.com/PeacefulNoob',
    followers_url: 'https://api.github.com/users/PeacefulNoob/followers',
    following_url:
      'https://api.github.com/users/PeacefulNoob/following{/other_user}',
    gists_url: 'https://api.github.com/users/PeacefulNoob/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/PeacefulNoob/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/PeacefulNoob/subscriptions',
    organizations_url: 'https://api.github.com/users/PeacefulNoob/orgs',
    repos_url: 'https://api.github.com/users/PeacefulNoob/repos',
    events_url: 'https://api.github.com/users/PeacefulNoob/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/PeacefulNoob/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'dervanovicaisa',
    id: 59751382,
    node_id: 'MDQ6VXNlcjU5NzUxMzgy',
    avatar_url: 'https://avatars.githubusercontent.com/u/59751382?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dervanovicaisa',
    html_url: 'https://github.com/dervanovicaisa',
    followers_url: 'https://api.github.com/users/dervanovicaisa/followers',
    following_url:
      'https://api.github.com/users/dervanovicaisa/following{/other_user}',
    gists_url: 'https://api.github.com/users/dervanovicaisa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/dervanovicaisa/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/dervanovicaisa/subscriptions',
    organizations_url: 'https://api.github.com/users/dervanovicaisa/orgs',
    repos_url: 'https://api.github.com/users/dervanovicaisa/repos',
    events_url: 'https://api.github.com/users/dervanovicaisa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/dervanovicaisa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'dsamfan',
    id: 75990504,
    node_id: 'MDQ6VXNlcjc1OTkwNTA0',
    avatar_url: 'https://avatars.githubusercontent.com/u/75990504?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dsamfan',
    html_url: 'https://github.com/dsamfan',
    followers_url: 'https://api.github.com/users/dsamfan/followers',
    following_url:
      'https://api.github.com/users/dsamfan/following{/other_user}',
    gists_url: 'https://api.github.com/users/dsamfan/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/dsamfan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dsamfan/subscriptions',
    organizations_url: 'https://api.github.com/users/dsamfan/orgs',
    repos_url: 'https://api.github.com/users/dsamfan/repos',
    events_url: 'https://api.github.com/users/dsamfan/events{/privacy}',
    received_events_url: 'https://api.github.com/users/dsamfan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cakkae',
    id: 9167784,
    node_id: 'MDQ6VXNlcjkxNjc3ODQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9167784?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cakkae',
    html_url: 'https://github.com/cakkae',
    followers_url: 'https://api.github.com/users/cakkae/followers',
    following_url: 'https://api.github.com/users/cakkae/following{/other_user}',
    gists_url: 'https://api.github.com/users/cakkae/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cakkae/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cakkae/subscriptions',
    organizations_url: 'https://api.github.com/users/cakkae/orgs',
    repos_url: 'https://api.github.com/users/cakkae/repos',
    events_url: 'https://api.github.com/users/cakkae/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cakkae/received_events',
    type: 'User',
    site_admin: false,
  },
];
